export const CHANGE_INPUT = 'CHANGE_INPUT'
export const CHANGE_IMAGE_URL = 'CHANGE_IMAGE_URL'
export const CHANGE_ROUTE = 'CHANGE_ROUTE'
export const SIGNUP_NAME = 'SIGNUP_NAME'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL'
export const SIGNUP_PASSWORD = 'SIGNUP_PASSWORD'
export const CHANGE_NAME_ERROR = 'CHANGE_NAME_ERROR'
export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'
export const TOGGLE_MODAL_STATE_GI = 'TOGGLE_MODAL_STATE_GI'
export const TOGGLE_MODAL_STATE_PER = 'TOGGLE_MODAL_STATE_PER'
export const TOGGLE_MODAL_STATE_RD = 'TOGGLE_MODAL_STATE_RD'
export const TOGGLE_MODAL_STATE_RP = 'TOGGLE_MODAL_STATE_RP'
export const TOGGLE_MODAL_STATE_PIC = 'TOGGLE_MODAL_STATE_PIC'
export const CHANGE_START_COLOR = 'CHANGE_START_COLOR'
export const CHANGE_NEW_PASSWORD = 'CHANGE_NEW_PASSWORD'
export const CHANGE_OLD_PASSWORD = 'CHANGE_OLD_PASSWORD'
export const CHANGE_CONFIRM_PASSWORD = 'CHANGE_CONFIRM_PASSWORD'
export const CHANGE_END_COLOR = 'CHANGE_END_COLOR'
export const CHANGE_AVATAR = 'CHANGE_AVATAR'
export const REQUEST_SIGNIN_PENDING = 'REQUEST_SIGNIN_PENDING'
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS'
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED'
export const REQUEST_SIGNUP_PENDING = 'REQUEST_SIGNUP_PENDING'
export const REQUEST_SIGNUP_SUCCESS = 'REQUEST_SIGNUP_SUCCESS'
export const REQUEST_SIGNUP_FAILED = 'REQUEST_SIGNUP_FAILED'
export const REQUEST_IMAGE_PENDING = 'REQUEST_IMAGE_PENDING'
export const REQUEST_IMAGE_SUCCESS = 'REQUEST_IMAGE_SUCCESS'
export const REQUEST_IMAGE_FAILED = 'REQUEST_IMAGE_FAILED'
export const REQUEST_FACES_PENDING = 'REQUEST_FACES_PENDING'
export const REQUEST_FACES_SUCCESS = 'REQUEST_FACES_SUCCESS'
export const REQUEST_FACES_FAILED = 'REQUEST_FACES_FAILED'
export const UPDATE_GENERAL_INFO_PENDING = 'UPDATE_GENERAL_INFO_PENDING'
export const UPDATE_GENERAL_INFO_SUCCESS = 'UPDATE_GENERAL_INFO_SUCCESS'
export const UPDATE_GENERAL_INFO_FAILED = 'UPDATE_GENERAL_INFO_FAILED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'
export const SIGNIN_API = "https://smart-brain-login-ts110798.herokuapp.com/signin"
export const SIGNUP_API = "https://smart-brain-login-ts110798.herokuapp.com/signup"
export const IMAGE_API = "https://smart-brain-login-ts110798.herokuapp.com/image"
export const FACE_DETECT_API = "https://face-detection-ts110798.herokuapp.com/api/v1/getfaces"
export const UPDATE_USER_API = "https://smart-brain-login-ts110798.herokuapp.com/update-user"
export const UPDATE_PASSWORD_API = "https://smart-brain-login-ts110798.herokuapp.com/update-password"
export const UPDATE_PERSONALIZATION_API = "https://smart-brain-login-ts110798.herokuapp.com/bg-theme"
export const UPDATE_AVATAR_API = "https://smart-brain-login-ts110798.herokuapp.com/profile-avatar"
// export const SIGNIN_API_LOCAL = "http://127.0.0.1:3001/signin"
// export const SIGNUP_API_LOCAL = "http://127.0.0.1:3001/signup"
// export const IMAGE_API_LOCAL = "http://127.0.0.1:3001/image"
// export const FACE_DETECT_API_LOCAL = "http://127.0.0.1:3002/api/v1/getfaces"
// export const UPDATE_USER_API_LOCAL = "http://127.0.0.1:3001/update-user"
// export const UPDATE_PASSWORD_API_LOCAL = "http://127.0.0.1:3001/update-password"
// export const UPDATE_PERSONALIZATION_API_LOCAL = "http://127.0.0.1:3001/bg-theme"
// export const UPDATE_AVATAR_API_LOCAL = "http://127.0.0.1:3001/profile-avatar"